// AUTO-GENERATED by scripts/codegen-types.mjs — DO NOT EDIT BY HAND.
// Source: apps/agent/src/interia/schemas.py

// ---- RoomState ----

export type AgentTraceEvent = {
  id: string;
  type: "plan" | "tool_call" | "tool_result" | "patch_applied" | "validation" | "user_decision";
  inputSummary: string;
  outputSummary: string;
  createdAt: string;
};

export type Bbox = {
  x: number;
  y: number;
  w: number;
  h: number;
};

export type CatalogItem = {
  id: string;
  name: string;
  category: "lamps" | "rugs" | "wall_decor" | "plants" | "textiles";
  compatibleStyles: string[];
  priceTier: "low" | "medium" | "high";
  materials: string[];
  visualEffect: string;
  placementSuggestions: string[];
  constraintsCompatibility: string[];
};

export type DesignPatch = _AddObjectPatch | _ModifyObjectPatch | _RemoveObjectPatch | _SetLockPatch | _PreservePatch;

export type DesignPlan = {
  palette: Palette;
  lightingPlan: string;
  decorSuggestions: CatalogItem[];
  layoutSuggestions: string[];
  actionPlan: string[];
  rationale: string;
  proposedPatches?: _AddObjectPatch | _ModifyObjectPatch | _RemoveObjectPatch | _SetLockPatch | _PreservePatch[];
};

export type DesignPreference = {
  style: "minimal" | "japandi" | "industrial" | "bohemian" | "warm-modern";
  budget: "low" | "medium" | "high";
  goal: "cozy" | "productive" | "elegant" | "spacious";
  constraints?: "keep-furniture" | "rental-friendly" | "no-drilling" | "pet-safe"[];
  freeformNotes?: string | null;
};

export type FidelityReport = {
  previewId: string;
  systemScore: number;
  cameraAnglePreserved: boolean;
  perObject: _FidelityPerObject[];
  styleApplied: _StyleApplied;
  unexpectedChanges?: string[];
  recommendedAction: "accept" | "regenerate_with_stronger_locks" | "ask_user_to_unlock";
  evidenceCrops?: _EvidenceCrop[] | null;
};

export type Grid = {
  rows?: 4;
  cols?: 4;
};

export type LockSet = {
  identity?: "locked" | "soft" | "editable";
  position?: "locked" | "soft" | "editable";
  appearance?: "locked" | "soft" | "editable";
};

export type Palette = {
  name: string;
  swatches: string[];
};

export type Preview = {
  id: string;
  imageUrl: string;
  promptSummary: string;
  generationProvider: "gemini-3-image-preview" | "mock";
  fromVersion: number;
  createdAt: string;
  userFidelityStatus?: "faithful" | "mostly" | "regenerate" | "manual-mark" | null;
};

export type RoomObject = {
  id: string;
  type: "window" | "bed" | "desk" | "chair" | "lamp" | "rug" | "plant" | "decor" | "textile" | "other";
  label: string;
  description: string;
  gridPosition: RootModel_Annotated_str__StringConstraints__;
  approximateSize: "small" | "medium" | "large";
  color?: string | null;
  material?: string | null;
  confidence: number;
  detectedBy: "vision" | "user";
  confirmedByUser?: boolean;
  evidenceCropUrl?: string | null;
  bbox?: Bbox | null;
};

export type RoomRelation = {
  subjectId: string;
  relation: "left_of" | "right_of" | "in_front_of" | "behind" | "above" | "under" | "attached_to_wall" | "centered_under" | "adjacent_to";
  targetId: string;
  confidence: number;
};

export type RoomShell = {
  roomType: "bedroom" | "studio" | "living" | "workspace" | "other";
  dimensionsHint?: "compact" | "medium" | "large" | null;
  cameraAngle: "front" | "corner-left" | "corner-right";
};

export type RoomSource = {
  imageUrl: string;
  sampleId?: "bedroom" | "studio" | "living" | "workspace" | null;
  uploadedAt: string;
};

export type RootModel_Annotated_str__StringConstraints__ = string;

export type _AddObjectPatch = {
  op: "add_object";
  target: Record<string, unknown>;
  reason: string;
};

export type _EvidenceCrop = {
  objectId: string;
  beforeUrl: string;
  afterUrl: string;
};

export type _FidelityPerObject = {
  objectId: string;
  label: string;
  preserved: boolean;
  confidence: number;
  note?: string | null;
};

export type _ModifyObjectPatch = {
  op: "modify_object";
  id: string;
  patch: Record<string, unknown>;
  reason: string;
};

export type _PreservePatch = {
  op: "preserve";
  id: string;
  reason: string;
};

export type _RemoveObjectPatch = {
  op: "remove_object";
  id: string;
  reason: string;
};

export type _SetLockPatch = {
  op: "set_lock";
  id: string;
  locks: Record<string, unknown>;
  reason: string;
};

export type _StyleApplied = {
  selected: string;
  applied: string;
  match: "strong" | "partial" | "weak";
};

export type RoomState = {
  version: number;
  source: RoomSource;
  shell: RoomShell;
  grid?: Grid;
  objects?: RoomObject[];
  relations?: RoomRelation[];
  editContract?: Record<string, LockSet>;
  preferences?: DesignPreference | null;
  designPlan?: DesignPlan | null;
  patches?: DesignPatch[];
  preview?: Preview | null;
  fidelity?: FidelityReport | null;
  trace?: AgentTraceEvent[];
};

// ---- RoomObject ----



// ---- RoomRelation ----



// ---- LockSet ----



// ---- DesignPreference ----



// ---- DesignPlan ----



// ---- DesignPatch ----



// ---- Preview ----



// ---- FidelityReport ----



// ---- AgentTraceEvent ----



// ---- CatalogItem ----


