#!/usr/bin/env node
/**
 * Generate apps/frontend/src/lib/interia/types.ts from the Pydantic models
 * exported by `apps/agent/src/interia/export_schema.py`.
 *
 * Usage: node scripts/codegen-types.mjs
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = process.cwd();
const agentDir = join(repoRoot, "apps", "agent");
const out = join(repoRoot, "apps", "frontend", "src", "lib", "interia", "types.ts");

const json = execFileSync(
  "uv",
  ["run", "python", "-m", "src.interia.export_schema"],
  { cwd: agentDir }
).toString();

const schemas = JSON.parse(json);

const banner = `// AUTO-GENERATED by scripts/codegen-types.mjs — DO NOT EDIT BY HAND.
// Source: apps/agent/src/interia/schemas.py

`;

function refName(ref) {
  return ref.split("/").pop();
}

function tsType(node, defs) {
  if (!node) return "unknown";
  if (node.$ref) return refName(node.$ref);
  if (node.enum) return node.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (node.const !== undefined) return JSON.stringify(node.const);
  if (node.anyOf) return node.anyOf.map((n) => tsType(n, defs)).join(" | ");
  if (node.oneOf) return node.oneOf.map((n) => tsType(n, defs)).join(" | ");
  if (node.allOf && node.allOf.length === 1) return tsType(node.allOf[0], defs);
  if (node.type === "array") return `${tsType(node.items, defs)}[]`;
  if (node.type === "object") {
    if (node.properties) {
      const required = new Set(node.required || []);
      const fields = Object.entries(node.properties).map(([k, v]) => {
        const opt = required.has(k) ? "" : "?";
        return `  ${k}${opt}: ${tsType(v, defs)};`;
      });
      return `{\n${fields.join("\n")}\n}`;
    }
    if (node.additionalProperties)
      return `Record<string, ${tsType(node.additionalProperties, defs)}>`;
    return "Record<string, unknown>";
  }
  if (node.type === "string") return "string";
  if (node.type === "integer" || node.type === "number") return "number";
  if (node.type === "boolean") return "boolean";
  if (node.type === "null") return "null";
  return "unknown";
}

function renderRoot(name, root) {
  const defs = root.$defs || {};
  const parts = [];
  for (const [defName, defNode] of Object.entries(defs)) {
    parts.push(`export type ${defName} = ${tsType(defNode, defs)};`);
  }
  parts.push(`export type ${name} = ${tsType(root, defs)};`);
  return parts.join("\n\n");
}

const seen = new Set();
const chunks = [];
for (const [name, root] of Object.entries(schemas)) {
  const block = renderRoot(name, root)
    .split("\n\n")
    .filter((stmt) => {
      const m = stmt.match(/^export type (\w+) =/);
      if (!m) return true;
      if (seen.has(m[1])) return false;
      seen.add(m[1]);
      return true;
    })
    .join("\n\n");
  chunks.push(`// ---- ${name} ----\n\n${block}`);
}

writeFileSync(out, banner + chunks.join("\n\n") + "\n");
console.log(`wrote ${out}`);
